//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeeView.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeeView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandGroupFile {
            get {
                return ResourceManager.GetString("CommandGroupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandLoadAs {
            get {
                return ResourceManager.GetString("CommandLoadAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandLoadAsMenu {
            get {
                return ResourceManager.GetString("CommandLoadAsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select and open the compressed file or image file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandLoadAsNote {
            get {
                return ResourceManager.GetString("CommandLoadAsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlFileNameBoxDirectoryNote {
            get {
                return ResourceManager.GetString("ControlFileNameBoxDirectoryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the path of the file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlFileNameBoxFileNote {
            get {
                return ResourceManager.GetString("ControlFileNameBoxFileNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlFileNameBoxSelectDirectory {
            get {
                return ResourceManager.GetString("ControlFileNameBoxSelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlFileNameBoxSelectFile {
            get {
                return ResourceManager.GetString("ControlFileNameBoxSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSusiePluginListConfig {
            get {
                return ResourceManager.GetString("ControlSusiePluginListConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSusiePluginListDown {
            get {
                return ResourceManager.GetString("ControlSusiePluginListDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSusiePluginListUp {
            get {
                return ResourceManager.GetString("ControlSusiePluginListUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogAddParameterTile {
            get {
                return ResourceManager.GetString("DialogAddParameterTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temporary folders can not be bookmarked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogBookmarkError {
            get {
                return ResourceManager.GetString("DialogBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not bookmark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogBookmarkErrorTitle {
            get {
                return ResourceManager.GetString("DialogBookmarkErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NeeView Startup error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogBootErrorTitle {
            get {
                return ResourceManager.GetString("DialogBootErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NeeView Startup options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogBootOptionTitle {
            get {
                return ResourceManager.GetString("DialogBootOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thumbnail cache deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogCacheDeletedTitle {
            get {
                return ResourceManager.GetString("DialogCacheDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no file that can be read in &quot;{0}&quot;. Do you also load subfolders or compressed files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogConfirmRecursive {
            get {
                return ResourceManager.GetString("DialogConfirmRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you also read subfolders? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogConfirmRecursiveTitle {
            get {
                return ResourceManager.GetString("DialogConfirmRecursiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogCopyErrorTitle {
            get {
                return ResourceManager.GetString("DialogCopyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogCopyImageErrorTitle {
            get {
                return ResourceManager.GetString("DialogCopyImageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete user data. Are you sure?
        ///
        ///The following data will be deleted
        ///- Setting file
        ///- History file
        ///- Bookmark file
        ///- Pagemark file
        ///- Cache file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDeleteApplicationData {
            get {
                return ResourceManager.GetString("DialogDeleteApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User data deleted. Quit NeeView. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDeleteApplicationDataComplete {
            get {
                return ResourceManager.GetString("DialogDeleteApplicationDataComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It has been deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDeleteApplicationDataCompleteTitle {
            get {
                return ResourceManager.GetString("DialogDeleteApplicationDataCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can not be deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDeleteApplicationDataErrorTitle {
            get {
                return ResourceManager.GetString("DialogDeleteApplicationDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete user data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDeleteApplicationDataTitle {
            get {
                return ResourceManager.GetString("DialogDeleteApplicationDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation can not be changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDragActionLockedTitle {
            get {
                return ResourceManager.GetString("DialogDragActionLockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize all drag operations. Is it OK? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDragActionReset {
            get {
                return ResourceManager.GetString("DialogDragActionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize the drag operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogDragActionResetTitle {
            get {
                return ResourceManager.GetString("DialogDragActionResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogExportErrorTitle {
            get {
                return ResourceManager.GetString("DialogExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export all settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogExportTitle {
            get {
                return ResourceManager.GetString("DialogExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to move this {0} to Recycle Bin? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileDelete {
            get {
                return ResourceManager.GetString("DialogFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete book に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileDeleteBookTitle {
            get {
                return ResourceManager.GetString("DialogFileDeleteBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete failed. Would you like to try again? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileDeleteError {
            get {
                return ResourceManager.GetString("DialogFileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete failed. Would you like to retry? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileDeleteErrorTitle {
            get {
                return ResourceManager.GetString("DialogFileDeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileDeletePageTitle {
            get {
                return ResourceManager.GetString("DialogFileDeletePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileDeleteTitle {
            get {
                return ResourceManager.GetString("DialogFileDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists.
        ///Would you like to rename it to {1}?  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameConfrict {
            get {
                return ResourceManager.GetString("DialogFileRenameConfrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file with the same name exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameConfrictTitle {
            get {
                return ResourceManager.GetString("DialogFileRenameConfrictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameErrorTitle {
            get {
                return ResourceManager.GetString("DialogFileRenameErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing the extension may make it impossible to use it.
        ///Is it OK?  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameExtension {
            get {
                return ResourceManager.GetString("DialogFileRenameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameExtensionTitle {
            get {
                return ResourceManager.GetString("DialogFileRenameExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to change the name. Would you like to try again? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameFailed {
            get {
                return ResourceManager.GetString("DialogFileRenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameFailedTitle {
            get {
                return ResourceManager.GetString("DialogFileRenameFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file name contains characters that can not be used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameInvalid {
            get {
                return ResourceManager.GetString("DialogFileRenameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified file name is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameWrong {
            get {
                return ResourceManager.GetString("DialogFileRenameWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified device name is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogFileRenameWrongDevice {
            get {
                return ResourceManager.GetString("DialogFileRenameWrongDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete all history. Is it OK? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogHistoryDeleteAll {
            get {
                return ResourceManager.GetString("DialogHistoryDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogHistoryDeleteAllTitle {
            get {
                return ResourceManager.GetString("DialogHistoryDeleteAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogHistoryDeletedTitle {
            get {
                return ResourceManager.GetString("DialogHistoryDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not get link. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogHyperLinkFailedTitle {
            get {
                return ResourceManager.GetString("DialogHyperLinkFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This image can not be output. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogImageExportError {
            get {
                return ResourceManager.GetString("DialogImageExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File save failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogImageExportErrorTitle {
            get {
                return ResourceManager.GetString("DialogImageExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogImportErrorTitle {
            get {
                return ResourceManager.GetString("DialogImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the item to be imported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogImportSelectTitle {
            get {
                return ResourceManager.GetString("DialogImportSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import all settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogImportTitle {
            get {
                return ResourceManager.GetString("DialogImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External application execution failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogOpenApplicationErrorTitle {
            get {
                return ResourceManager.GetString("DialogOpenApplicationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The location of the setting file can not be opened with the store application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogOpenSettingFolderError {
            get {
                return ResourceManager.GetString("DialogOpenSettingFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This command can not be used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogOpenSettingFolderErrorTitle {
            get {
                return ResourceManager.GetString("DialogOpenSettingFolderErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temporary folders can not be pagemarked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogPagemarkError {
            get {
                return ResourceManager.GetString("DialogPagemarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not pagemark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogPagemarkErrorTitle {
            get {
                return ResourceManager.GetString("DialogPagemarkErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnumLanguageEnglish {
            get {
                return ResourceManager.GetString("EnumLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnumLanguageJapanese {
            get {
                return ResourceManager.GetString("EnumLanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System manages memory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsAutoGC {
            get {
                return ResourceManager.GetString("IsAutoGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When it is OFF, memory is released every time page is switched に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsAutoGCTips {
            get {
                return ResourceManager.GetString("IsAutoGCTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title bar operation at full screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCaptionEmulateInFullScreen {
            get {
                return ResourceManager.GetString("IsCaptionEmulateInFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable the title bar operation (double click and drag) on ​​the menu at full screen. &quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsCaptionEmulateInFullScreenTips {
            get {
                return ResourceManager.GetString("IsCaptionEmulateInFullScreenTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamArchiverMediaIsEnabled {
            get {
                return ResourceManager.GetString("ParamArchiverMediaIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video file extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamArchiverMediaSupportFileTypes {
            get {
                return ResourceManager.GetString("ParamArchiverMediaSupportFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Probably what you can play with Windows Media Player is playable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamArchiverMediaSupportFileTypesTips {
            get {
                return ResourceManager.GetString("ParamArchiverMediaSupportFileTypesTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamArchiverPdfIsEnabled {
            get {
                return ResourceManager.GetString("ParamArchiverPdfIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF page standard size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamArchiverPdfRenderSize {
            get {
                return ResourceManager.GetString("ParamArchiverPdfRenderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normally we will render according to the display size, but the lower limit will be this standard size. If it becomes smaller, it is reduced and displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamArchiverPdfRenderSizeTips {
            get {
                return ResourceManager.GetString("ParamArchiverPdfRenderSizeTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF file extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamArchiverPdfSupportFileTypes {
            get {
                return ResourceManager.GetString("ParamArchiverPdfSupportFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time (in seconds) until panel and menu disappear automatically に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamAutoHideDelayTime {
            get {
                return ResourceManager.GetString("ParamAutoHideDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDownloadPath {
            get {
                return ResourceManager.GetString("ParamDownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is a storage place of the image dropped by the browser etc. If not specified, temporary folder is used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamDownloadPathTips {
            get {
                return ResourceManager.GetString("ParamDownloadPathTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of page operations to start history registration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamHistoryEntryPageCount {
            get {
                return ResourceManager.GetString("ParamHistoryEntryPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register in history with page movement operation more than this count or last page display. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamHistoryEntryPageCountTips {
            get {
                return ResourceManager.GetString("ParamHistoryEntryPageCountTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand all recursive compressed files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsArchiveRecursive {
            get {
                return ResourceManager.GetString("ParamIsArchiveRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If it is set to OFF, the included compressed file will be handled as subfolder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsArchiveRecursiveTips {
            get {
                return ResourceManager.GetString("ParamIsArchiveRecursiveTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start playing slideshow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsAutoPlaySlideShow {
            get {
                return ResourceManager.GetString("ParamIsAutoPlaySlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load a subfolder if there is no page and only one subfolder exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsAutoRecursive {
            get {
                return ResourceManager.GetString("ParamIsAutoRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determine including out-of-page files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsAutoRecursiveWithAllFiles {
            get {
                return ResourceManager.GetString("ParamIsAutoRecursiveWithAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic judgment will not be performed if there are files other than files to become pages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsAutoRecursiveWithAllFilesTips {
            get {
                return ResourceManager.GetString("ParamIsAutoRecursiveWithAllFilesTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset display interval with mouse move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsCancelSlideByMouseMove {
            get {
                return ResourceManager.GetString("ParamIsCancelSlideByMouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When set to OFF, it will only be reset by clear action such as clicking. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsCancelSlideByMouseMoveTips {
            get {
                return ResourceManager.GetString("ParamIsCancelSlideByMouseMoveTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If there is no page, inquire whether to read the subfolder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsConfirmRecursive {
            get {
                return ResourceManager.GetString("ParamIsConfirmRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If there is no page that can be displayed when the book is opened, and a subfolder exists, a dialog is displayed asking whether to load the subfolder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsConfirmRecursiveTips {
            get {
                return ResourceManager.GetString("ParamIsConfirmRecursiveTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not save history, bookmarks, pagemarks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsDisableSave {
            get {
                return ResourceManager.GetString("ParamIsDisableSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book information is not saved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsDisableSaveTips {
            get {
                return ResourceManager.GetString("ParamIsDisableSaveTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File operation enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsFileOperationEnabled {
            get {
                return ResourceManager.GetString("ParamIsFileOperationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dot-by-dot display of image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsIgnoreImageDpi {
            get {
                return ResourceManager.GetString("ParamIsIgnoreImageDpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When displaying in original size, make it match with display pixels without depending on DPI. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsIgnoreImageDpiTips {
            get {
                return ResourceManager.GetString("ParamIsIgnoreImageDpiTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save recursive compressed file in history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsInnerArchiveHistoryEnabled {
            get {
                return ResourceManager.GetString("ParamIsInnerArchiveHistoryEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow multiple activations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsMultiBootEnabled {
            get {
                return ResourceManager.GetString("ParamIsMultiBootEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow network access に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsNetworkEnabled {
            get {
                return ResourceManager.GetString("ParamIsNetworkEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In this application, we will use the network only for WEB links such as version update confirmation and online help from &quot;About&quot; dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsNetworkEnabledTips {
            get {
                return ResourceManager.GetString("ParamIsNetworkEnabledTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore an open book に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsOpenLastBook {
            get {
                return ResourceManager.GetString("ParamIsOpenLastBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display confirmation dialog at file deletion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsRemoveConfirmed {
            get {
                return ResourceManager.GetString("ParamIsRemoveConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore the second window coordinates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsRestoreSecondWindow {
            get {
                return ResourceManager.GetString("ParamIsRestoreSecondWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Also restore window coordinates when duplicates are activated. When set to OFF, it is displayed in the initial coordinates. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsRestoreSecondWindowTips {
            get {
                return ResourceManager.GetString("ParamIsRestoreSecondWindowTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore full screen state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsSaveFullScreen {
            get {
                return ResourceManager.GetString("ParamIsSaveFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore window coordinates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsSaveWindowPlacement {
            get {
                return ResourceManager.GetString("ParamIsSaveWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make a backup of the user setting file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsSettingBackup {
            get {
                return ResourceManager.GetString("ParamIsSettingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make a backup of the configuration file and load it instead if the normal configuration file can not be read. The file name is UserSetting.xaml.old. The update timing is when you close the setting window and when you exit the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsSettingBackupTips {
            get {
                return ResourceManager.GetString("ParamIsSettingBackupTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsSlideShowByLoop {
            get {
                return ResourceManager.GetString("ParamIsSlideShowByLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After playing to the last page, it will return to the first page. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsSlideShowByLoopTips {
            get {
                return ResourceManager.GetString("ParamIsSlideShowByLoopTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save UNC path in history に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsUncHistoryEnabled {
            get {
                return ResourceManager.GetString("ParamIsUncHistoryEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the path on the network like &quot;\\computer\~&quot; in the history. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamIsUncHistoryEnabledTips {
            get {
                return ResourceManager.GetString("ParamIsUncHistoryEnabledTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamLanguage {
            get {
                return ResourceManager.GetString("ParamLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * It is applied from the next startup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamLanguageTips {
            get {
                return ResourceManager.GetString("ParamLanguageTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change time in page movement (seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamPageSeconds {
            get {
                return ResourceManager.GetString("ParamPageSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use compressed file expansion with 7-Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverIsEnabled {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre Extract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverIsPreExtract {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverIsPreExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When you browse books, you can speed up page feed by pre-extracting everything to a temporary folder. When OFF, pre-extraction is performed only for solid compressed files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverIsPreExtractTips {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverIsPreExtractTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time to lock file (sec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverLockTime {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverLockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you do not have access at this time, unlock it. -1 holds the lock. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverLockTimeTips {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverLockTimeTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum file size to be extracted in advance (MB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverPreExtractSolidSize {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverPreExtractSolidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressed files exceeding this size will not be pre-extracted. Set 0 to prohibit all pre-extraction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverPreExtractSolidSizeTips {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverPreExtractSolidSizeTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressed file extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverSupportFileTypes {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverSupportFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location of 7z.dll (64 bit) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverX64DllPath {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverX64DllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set this if you want to use another 7z.dll. To reflect, you need to reopen the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverX64DllPathTips {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverX64DllPathTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location of 7z.dll (32bit) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverX86DllPath {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverX86DllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set this if you want to use another 7z.dll. To reflect, you need to reopen the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSevenZipArchiverX86DllPathTips {
            get {
                return ResourceManager.GetString("ParamSevenZipArchiverX86DllPathTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display interval (sec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSlideShowInterval {
            get {
                return ResourceManager.GetString("ParamSlideShowInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the Susie plugin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSusieIsEnabled {
            get {
                return ResourceManager.GetString("ParamSusieIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prioritize Susie plugin in compressed file expansion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSusieIsFirstOrderSusieArchive {
            get {
                return ResourceManager.GetString("ParamSusieIsFirstOrderSusieArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prioritize Susie plugin in image display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSusieIsFirstOrderSusieImage {
            get {
                return ResourceManager.GetString("ParamSusieIsFirstOrderSusieImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamSusiePluginPath {
            get {
                return ResourceManager.GetString("ParamSusiePluginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window frame with title bar hidden に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamWindowChromeFrame {
            get {
                return ResourceManager.GetString("ParamWindowChromeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use ZIP compressed file expansion with standard function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamZipArchiverIsEnabled {
            get {
                return ResourceManager.GetString("ParamZipArchiverIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compressed file extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamZipArchiverSupportFileTypes {
            get {
                return ResourceManager.GetString("ParamZipArchiverSupportFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only zip format is supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParamZipArchiverSupportFileTypesTips {
            get {
                return ResourceManager.GetString("ParamZipArchiverSupportFileTypesTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete all data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingItemRemove {
            get {
                return ResourceManager.GetString("SettingItemRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete the user data and exit the application. It is used when you want to completely delete history etc. before uninstallation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingItemRemoveTips {
            get {
                return ResourceManager.GetString("SettingItemRemoveTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchive {
            get {
                return ResourceManager.GetString("SettingPageArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiveMedia {
            get {
                return ResourceManager.GetString("SettingPageArchiveMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiveMediaAdvance {
            get {
                return ResourceManager.GetString("SettingPageArchiveMediaAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiveMediaFeature {
            get {
                return ResourceManager.GetString("SettingPageArchiveMediaFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchivePdf {
            get {
                return ResourceManager.GetString("SettingPageArchivePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchivePdfAdvance {
            get {
                return ResourceManager.GetString("SettingPageArchivePdfAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchivePdfFeature {
            get {
                return ResourceManager.GetString("SettingPageArchivePdfFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7-Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiverSevenZip {
            get {
                return ResourceManager.GetString("SettingPageArchiverSevenZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiverSevenZipAdvance {
            get {
                return ResourceManager.GetString("SettingPageArchiverSevenZipAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiverSevenZipFeature {
            get {
                return ResourceManager.GetString("SettingPageArchiverSevenZipFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiveZip {
            get {
                return ResourceManager.GetString("SettingPageArchiveZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiveZipAdvance {
            get {
                return ResourceManager.GetString("SettingPageArchiveZipAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageArchiveZipFeature {
            get {
                return ResourceManager.GetString("SettingPageArchiveZipFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneral {
            get {
                return ResourceManager.GetString("SettingPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralBoot {
            get {
                return ResourceManager.GetString("SettingPageGeneralBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralBootBoot {
            get {
                return ResourceManager.GetString("SettingPageGeneralBootBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralBootBootDetail {
            get {
                return ResourceManager.GetString("SettingPageGeneralBootBootDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * This setting will be reflected after closing the setting screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralBootBootDetailTips {
            get {
                return ResourceManager.GetString("SettingPageGeneralBootBootDetailTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * This setting will be reflected after closing the setting screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralBootBootTips {
            get {
                return ResourceManager.GetString("SettingPageGeneralBootBootTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralDetail {
            get {
                return ResourceManager.GetString("SettingPageGeneralDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralDetailDetail {
            get {
                return ResourceManager.GetString("SettingPageGeneralDetailDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralRemove {
            get {
                return ResourceManager.GetString("SettingPageGeneralRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete user data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageGeneralRemoveRemove {
            get {
                return ResourceManager.GetString("SettingPageGeneralRemoveRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Susie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageSusie {
            get {
                return ResourceManager.GetString("SettingPageSusie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive plug-in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageSusieArchivePlugin {
            get {
                return ResourceManager.GetString("SettingPageSusieArchivePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Susie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageSusieGeneral {
            get {
                return ResourceManager.GetString("SettingPageSusieGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageSusieGeneralGeneral {
            get {
                return ResourceManager.GetString("SettingPageSusieGeneralGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageSusieGeneralPriority {
            get {
                return ResourceManager.GetString("SettingPageSusieGeneralPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image plug-in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageSusieImagePlugin {
            get {
                return ResourceManager.GetString("SettingPageSusieImagePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordAdd {
            get {
                return ResourceManager.GetString("WordAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordCancel {
            get {
                return ResourceManager.GetString("WordCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordCause {
            get {
                return ResourceManager.GetString("WordCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordCommand {
            get {
                return ResourceManager.GetString("WordCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordDelete {
            get {
                return ResourceManager.GetString("WordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordDescription {
            get {
                return ResourceManager.GetString("WordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordExport {
            get {
                return ResourceManager.GetString("WordExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordExtension {
            get {
                return ResourceManager.GetString("WordExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordFile {
            get {
                return ResourceManager.GetString("WordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordFolder {
            get {
                return ResourceManager.GetString("WordFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordImport {
            get {
                return ResourceManager.GetString("WordImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordItem {
            get {
                return ResourceManager.GetString("WordItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordMainMenu {
            get {
                return ResourceManager.GetString("WordMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordNo {
            get {
                return ResourceManager.GetString("WordNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordOff {
            get {
                return ResourceManager.GetString("WordOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordOK {
            get {
                return ResourceManager.GetString("WordOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordOn {
            get {
                return ResourceManager.GetString("WordOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordRemove {
            get {
                return ResourceManager.GetString("WordRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordRename {
            get {
                return ResourceManager.GetString("WordRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordRetry {
            get {
                return ResourceManager.GetString("WordRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordYes {
            get {
                return ResourceManager.GetString("WordYes", resourceCulture);
            }
        }
    }
}
