# This is a basic workflow to help you get started with Actions
name: Build

# Controls when the action will run. 
on:
  push:
    branches:
      - karma_dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: windows-2022
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: .\build.bat

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: .\NeeView.7z
